server:
  port: 8077
  servlet.context-path: /Music
  tomcat.uri-encoding: UTF-8

#配置web页面入口
magic-api:
  web: /magic/web
#配置文件存储位置。当以classpath开头时，为只读模式
  resource:
    location: classpath:config

spring:
  profiles:
    active: mybatis
  application:
    name: OnlineMusic
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tp_music?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: 123456

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: WEB-INF/**

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

logging:
  config: classpath:config/logback-spring.xml
  level:
    #指定包日志级别
    cn.wikitang.onlinemusic.dao: info
    #开启myabtis语句打印
    main.blog.mapper: trace

knife4j:
#  开启生产环境屏蔽
#  production: true
#  增强功能需要通过配置yml配置文件开启增强
  enable: true
  basic:
    enable: true
    username: admin
    password: 123456
